global:
  scrape_interval: 15s 

scrape_configs:
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  
  - job_name: 'url-shortener-api'
    static_configs:
      - targets: ['host.docker.internal:5099'] 
  
  - job_name: 'sql-server'
    static_configs:
      - targets: ['sql-exporter:4000'] # 'sql-exporter' é o nome do serviço do exportador
